### ISSUE TITLE
Error in snpInsideRuns, even after fix

### ISSUE THREAD

**Issue by cbossu** [bioinformatics-ptp/detectRUNS#18] opened 2020-12-11 20:38 UTC
I receive a bug when trying to create the Manhattan plot of sequential runs:
|                                                    |   0%
Error in snpInsideRunsCpp(runsChrom, mapChrom, genotypeFile) : 
Expecting a string vector: [type=double; required=STRSXP].

I read in the past this had to do with having a string in the chr name, but I fixed this, so the chromosomes are numeric (I now have 31 chromosomes), and yet I still get this error.

The code I use is: 
plot_manhattanRuns(slidingRuns, genotypeFile = genotypeFilePath, mapFile = mapFilePath, savePlots = T, plotTitle = "ROHom")

I'm using detectRuns 0.9.6 on MacBookPro, Rstudio, R version 4.0.2. 

It's just this plot that fails. The other plots seem to work ok. If you have any insights, let me know. Cheers,

Christen

**Comment by bunop** [comment] 2020-12-12 16:21
Dear @cbossu ,

Thank you for your interest in `detectRUNS`.  Regarding your error:
>I read in the past this had to do with having a string in the chr name, but I fixed this, so the chromosomes are numeric (I now have 31 chromosomes), and yet I still get this error.

Hmm, I think we made some confusion in this step in particoular. However, the error message you received tell you that it was expecting a string value, not a number. I don't have your data, so the best I can do is trying to guess your error:
```R
# this will execute the full example
example("plot_manhattanRuns")
# this will ri-execute only plot_manhattanRuns and works
plot_manhattanRuns(runs = runsDF, genotypeFile = genotypeFile, mapFile = mapFile, savePlots = FALSE, plotTitle = "ROHom")
# let's change `chrom` in numeric
runsDF$chrom = as.numeric(runsDF$chrom)
# calling plot_manhattanRuns
plot_manhattanRuns(runs = runsDF, genotypeFile = genotypeFile, mapFile = mapFile, savePlots = FALSE, plotTitle = "ROHom")
[1] "Calculation % SNP in ROH"
[1] "Chromosome founds:  2"
  |                                                                                                                                                          |   0%
 Show Traceback
 
 Rerun with Debug
 Error in snpInsideRunsCpp(runsChrom, mapChrom, genotypeFile) : 
  Expecting a string vector: [type=double; required=STRSXP]. 
```
Is that your case? by converting back the same column as a string, I can redo the graphs:
```R
runsDF$chrom = as.character(runsDF$chrom)
# now the plot works as expected
plot_manhattanRuns(runs = runsDF, genotypeFile = genotypeFile, mapFile = mapFile, savePlots = FALSE, plotTitle = "ROHom")
```
This is because the function `snpInsideRunsCpp` is expecting to covert into [integer a character vector](https://github.com/bioinformatics-ptp/detectRUNS/blob/bdc3adf2b150716f447892bf913c8ef6f60a12e7/detectRUNS/src/functions.cpp#L927). *It is true that we suppose to work with numeric chromosomes, however this chromosomes are expected to be strings inside `plot_manhattanRuns`*.

@cbossu , could you convert your chromosomes as characters (ex. `slidingRuns$chrom = as.character(slidingRuns$chrom)` and tell us if it works or not? If it doesn't work, could you send us minimal example files so we can try to reproduce your errors?

**Comment by cbossu** [comment] 2020-12-16 01:06
Hello. Thanks for the potential fix-- I was so hopeful. Your fix did change the chrom to character, but I'm getting the same error. I've attached a map and ped file that includes just two chromosomes, so maybe it has something to do with the map file specifically (I label my SNPs as scaf.pos, but I don't see how this would result in the error). 

Just to show the character designation: 
class(slidingRuns$chrom)
[1] "character"

but the error when running: 
plot_manhattanRuns(slidingRuns, genotypeFile = genotypeFilePath, mapFile = mapFilePath, savePlots = F, plotTitle = "ROHom")

[1] "Calculation % SNP in ROH"
[1] "Chromosome founds:  2"
  |   |   0%Error in snpInsideRunsCpp(runsChrom, mapChrom, genotypeFile) : 
  Expecting a string vector: [type=double; required=STRSXP].

Let me know if you need anything else from me. Best,

Christen



[BUOW.2chr_test.map.txt](https://github.com/bioinformatics-ptp/detectRUNS/files/5699637/BUOW.2chr_test.map.txt)
[BUOW.2chr_test.ped.txt](https://github.com/bioinformatics-ptp/detectRUNS/files/5699640/BUOW.2chr_test.ped.txt)

**Comment by bunop** [comment] 2020-12-16 09:07
Dear @cbossu ,

Thank you again for reporting this. Yes, you are correct: this issue is related with your `.map` file in particoular because [snpInsideRunsCpp](https://github.com/bioinformatics-ptp/detectRUNS/blob/bdc3adf2b150716f447892bf913c8ef6f60a12e7/detectRUNS/src/functions.cpp#L926) is expecting to find a `character` value for `SNP_NAME` but such column is read as numeric value by [fread in plot_manhattanRuns](https://github.com/bioinformatics-ptp/detectRUNS/blob/bdc3adf2b150716f447892bf913c8ef6f60a12e7/detectRUNS/R/plots.R#L423). This thing need to be fixed in our code or in a new package version in order to get things done.

Btw, you could change the `SNP_NAME` column in your `.map` file in order to be read as character. In your example you have:

```
8       8.352443        0       352443
8       8.352466        0       352466
8       8.352474        0       352474
...
```

`8.352443` is read as `numeric` while it should be read as `character`. We can change name, for example, using `sed` in **bash** by replacing `.` with `:` (like positions in genome browser). This is sufficient to make `data::table.fread` interpreting this column as `character`:

```
$ sed 's/\./:/' BUOW.2chr_test.map.txt >> BUOW.2chr_test.map.fix.txt
```

Now your file will look different for `SNP_NAME` column:

```
8       8:352443        0       352443
8       8:352466        0       352466
8       8:352474        0       352474
...
```

And now you can calculate your manhattan plots with `R` using the **fixed** map file:

```R
library("detectRUNS")

genotypeFilePath <- "BUOW.2chr_test.ped.txt"

# This will raise errors in plot_manhattanRuns
# mapFilePath <- "BUOW.2chr_test.map.txt"

# This is the same file as before but with `SNP_NAME` column fixed
mapFilePath <- "BUOW.2chr_test.map.fix.txt"

# calculate slidingRuns (with example parameters)
slidingRuns <- slidingRUNS.run(
  genotypeFilePath, mapFilePath, windowSize = 15, threshold = 0.1,
  minSNP = 15, ROHet = FALSE,  maxOppWindow = 1, maxMissWindow = 1, maxGap=10^6,
  minLengthBps = 100000,  minDensity = 1/10000)

# do graphs
plot_manhattanRuns(slidingRuns, genotypeFile = genotypeFilePath, mapFile = mapFilePath, savePlots = F, plotTitle = "ROHom")
```

@cbossu , would you like to test if this trick and report to us if it works?

**Comment by cbossu** [comment] 2020-12-16 21:30
That fix did the charm! Thank you so much!

Christen

**Closed** 2022-03-22 16:59 UTC
Labels: bug
